services:
  sonarqube-custom:
    build: .
    ports:
      -  "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - ./scripts:/opt/sonarqube/scripts
    healthcheck:
      test: "curl -s -X GET localhost:9000/api/system/status"
      interval: 5s
      timeout: 3s
      retries: 30
    entrypoint: ["bash", "./scripts/entrypoint.bash"]

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins: